<?php

namespace Codebender\ProjectBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * ProjectFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectFileRepository extends DocumentRepository
{
}